extend-exclude = ["kmk/"]
line-length = 120
indent-width = 4
target-version = "py310"
ignore-init-module-imports = true

[lint]
extend-ignore = ["TRY003"]
select = ["E", "F", "UP", "B", "SIM", "I", "ASYNC", "TD", "TRY"]

[lint.isort]
case-sensitive = true
known-third-party = ["kmk"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
