from kmk.extensions.media_keys import MediaKeys
from kmk.keys import KC
from kmk.modules.capsword import CapsWord
from kmk.modules.layers import Layers
from kmk.modules.mouse_keys import MouseKeys
from kmk.modules.power import Power
from kmk.modules.tapdance import TapDance
from kmk.modules.holdtap import HoldTap


def configure(keyboard):
    keyboard.modules.append(Layers())
    keyboard.modules.append(MouseKeys())
    keyboard.modules.append(Power())
    keyboard.modules.append(TapDance())
    keyboard.extensions.append(MediaKeys())
    keyboard.modules.append(CapsWord())
    keyboard.modules.append(HoldTap())

    tt = {"tap_time": 300}
    nph = dict(prefer_hold=False, tap_interrupted=True, **tt)
    ph = dict(prefer_hold=True, tap_interrupted=False, **tt)

    A_ord = ord("A")
    for alpha in range(26):
        globals()[chr(alpha + A_ord)] = getattr(KC, chr(alpha + A_ord))
    for name in {
        "HT",
        "LT",
        "LGUI",
        "LALT",
        "LCTL",
        "LSFT",
        "RALT",
        "RCTL",
        "RSFT",
        "RGUI",
        "SLSH",
        "QUOT",
        "DEL",
        "INS",
        "DF"
    }:
        globals()[name] = getattr(KC, name)

    XX = KC.NO

    keyboard.keymap = [
        # BASE
        [
        XX,                   Q,                   W,                   F,                   P,                   B,                                                                                                       J,                   L,                   U,                   Y,                 QUOT,                 XX,
        XX,          HT(A, LGUI, **nph),  HT(R, LALT, **nph),  HT(S, LCTL, **nph),  HT(T, LSFT, **nph),           G,                                                                                                       K,          HT(N, LSFT, **nph),  HT(E, LCTL, **nph),  HT(I, LALT, **nph),  HT(O, LGUI, **nph),          XX,
        XX,            LT(3, Z, **ph),    HT(X, RALT, **nph),           C,                   D,                   V,                  XX,                                       XX,                  XX,                   M,                   H,                KC.COMM,       HT(KC.DOT, RALT, **nph),  LT(3, SLSH, **ph),
                                                  XX,          LT(6, KC.ESC, **ph), LT(4, KC.SPC, **ph), LT(5, KC.TAB, **ph),         XX,                                                            XX,          LT(8, KC.ENT, **ph), LT(7, KC.BSPC, **ph),  LT(9, DEL, **ph),           XX,
        ],
        # EXTRA
        [
            XX,
            Q,
            W,
            E,
            R,
            T,
            Y,
            U,
            I,
            O,
            P,
            XX,
            XX,
            HT(A, LGUI, **nph),
            HT(S, LALT, **nph),
            HT(D, LCTL, **nph),
            HT(F, LSFT, **nph),
            G,
            H,
            HT(J, LSFT, **nph),
            HT(K, LCTL, **nph),
            HT(L, LALT, **nph),
            HT(QUOT, LGUI, **nph),
            XX,
            XX,
            LT(3, Z, **ph),
            HT(X, RALT, **nph),
            C,
            V,
            B,
            XX,
            XX,
            XX,
            XX,
            N,
            M,
            KC.COMM,
            HT(KC.DOT, RALT, **nph),
            LT(3, SLSH, **ph),
            XX,
            XX,
            LT(6, KC.ESC, **ph),
            LT(4, KC.SPC, **ph),
            LT(5, KC.TAB, **ph),
            XX,
            XX,
            LT(8, KC.ENT, **ph),
            LT(7, KC.BSPC, **ph),
            LT(9, DEL, **ph),
            XX,
        ],
        # TAP
        [
            XX,
            Q,
            W,
            F,
            P,
            B,
            J,
            L,
            U,
            Y,
            QUOT,
            XX,
            XX,
            A,
            R,
            S,
            T,
            G,
            M,
            N,
            E,
            I,
            O,
            XX,
            XX,
            Z,
            X,
            C,
            D,
            V,
            XX,
            XX,
            XX,
            XX,
            K,
            H,
            KC.COMM,
            KC.DOT,
            SLSH,
            XX,
            XX,
            KC.ESC,
            KC.SPC,
            KC.TAB,
            XX,
            XX,
            KC.ENT,
            KC.BSPC,
            DEL,
            XX,
        ],
        # BUTTON
        [
            XX,
            XX,
            LSFT(DEL),
            LCTL(INS),
            LSFT(INS),
            XX,
            XX,
            LSFT(INS),
            LCTL(INS),
            LSFT(DEL),
            XX,
            XX,
            XX,
            LGUI,
            LALT,
            LCTL,
            LSFT,
            XX,
            XX,
            LSFT,
            LCTL,
            LALT,
            LGUI,
            XX,
            XX,
            XX,
            LSFT(DEL),
            LCTL(INS),
            LSFT(INS),
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            LSFT(INS),
            LCTL(INS),
            LSFT(DEL),
            XX,
            XX,
            XX,
            KC.MB_MMB,
            KC.MB_LMB,
            KC.MB_RMB,
            XX,
            XX,
            KC.MB_RMB,
            KC.MB_LMB,
            KC.MB_MMB,
            XX,
        ],
        # NAV
        [
            XX,
            KC.TD(XX, KC.RELOAD, **tt),
            KC.TD(XX, DF(2), **tt),
            KC.TD(XX, DF(1), **tt),
            KC.TD(XX, DF(0), **tt),
            XX,
            XX,
            LSFT(INS),
            LCTL(INS),
            LSFT(DEL),
            XX,
            XX,
            XX,
            LGUI,
            LALT,
            LCTL,
            LSFT,
            XX,
            KC.TD(KC.CW, KC.CAPS, **tt),
            KC.LEFT,
            KC.DOWN,
            KC.UP,
            KC.RGHT,
            XX,
            XX,
            XX,
            RALT,
            KC.TD(XX, DF(7), **tt),
            KC.TD(XX, DF(4), **tt),
            XX,
            XX,
            XX,
            XX,
            XX,
            INS,
            KC.HOME,
            KC.PGDN,
            KC.PGUP,
            KC.END,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            KC.ENT,
            KC.BSPC,
            DEL,
            XX,
        ],
        # MOUSE
        [
            XX,
            KC.TD(XX, KC.RELOAD, **tt),
            KC.TD(XX, DF(2), **tt),
            KC.TD(XX, DF(1), **tt),
            KC.TD(XX, DF(0), **tt),
            XX,
            XX,
            LSFT(INS),
            LCTL(INS),
            LSFT(DEL),
            XX,
            XX,
            XX,
            LGUI,
            LALT,
            LCTL,
            LSFT,
            XX,
            XX,
            KC.MS_LT,
            KC.MS_DN,
            KC.MS_UP,
            KC.MS_RT,
            XX,
            XX,
            XX,
            RALT,
            KC.TD(XX, DF(8), **tt),
            KC.TD(XX, DF(5), **tt),
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            KC.MW_DN,
            KC.MW_UP,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            KC.MB_RMB,
            KC.MB_LMB,
            KC.MB_MMB,
            XX,
        ],
        # MEDIA
        [
            XX,
            KC.TD(XX, KC.RELOAD, **tt),
            KC.TD(XX, DF(2), **tt),
            KC.TD(XX, DF(1), **tt),
            KC.TD(XX, DF(0), **tt),
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            LGUI,
            LALT,
            LCTL,
            LSFT,
            XX,
            KC.PS_TOG,
            KC.MPRV,
            KC.VOLD,
            KC.VOLU,
            KC.MNXT,
            XX,
            XX,
            XX,
            RALT,
            KC.TD(XX, DF(9), **tt),
            KC.TD(XX, DF(6), **tt),
            XX,
            XX,
            XX,
            XX,
            XX,
            KC.HID,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            KC.MSTP,
            KC.MPLY,
            KC.MUTE,
            XX,
        ],
        # NUM
        [
            XX,
            KC.LBRC,
            KC.N7,
            KC.N8,
            KC.N9,
            KC.RBRC,
            XX,
            KC.TD(XX, DF(0), **tt),
            KC.TD(XX, DF(1), **tt),
            KC.TD(XX, DF(2), **tt),
            KC.TD(XX, KC.RELOAD, **tt),
            XX,
            XX,
            KC.SCLN,
            KC.N4,
            KC.N5,
            KC.N6,
            KC.EQL,
            XX,
            LSFT,
            LCTL,
            LALT,
            LGUI,
            XX,
            XX,
            KC.GRV,
            KC.N1,
            KC.N2,
            KC.N3,
            KC.BSLS,
            XX,
            XX,
            XX,
            XX,
            XX,
            KC.TD(XX, DF(7), **tt),
            KC.TD(XX, DF(4), **tt),
            RALT,
            XX,
            XX,
            XX,
            KC.DOT,
            KC.N0,
            KC.MINS,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
        ],
        # SYM
        [
            XX,
            KC.LCBR,
            KC.AMPR,
            KC.ASTR,
            KC.LPRN,
            KC.RCBR,
            XX,
            KC.TD(XX, DF(0), **tt),
            KC.TD(XX, DF(1), **tt),
            KC.TD(XX, DF(2), **tt),
            KC.TD(XX, KC.RELOAD, **tt),
            XX,
            XX,
            KC.COLN,
            KC.DLR,
            KC.PERC,
            KC.CIRC,
            KC.PLUS,
            XX,
            LSFT,
            LCTL,
            LALT,
            LGUI,
            XX,
            XX,
            KC.TILD,
            KC.EXLM,
            KC.AT,
            KC.HASH,
            KC.PIPE,
            XX,
            XX,
            XX,
            XX,
            XX,
            KC.TD(XX, DF(8), **tt),
            KC.TD(XX, DF(5), **tt),
            RALT,
            XX,
            XX,
            XX,
            KC.LPRN,
            KC.RPRN,
            KC.UNDS,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
        ],
        # FUN
        [
            XX,
            KC.F12,
            KC.F7,
            KC.F8,
            KC.F9,
            KC.PSCR,
            XX,
            KC.TD(XX, DF(0), **tt),
            KC.TD(XX, DF(1), **tt),
            KC.TD(XX, DF(2), **tt),
            KC.TD(XX, KC.RELOAD, **tt),
            XX,
            XX,
            KC.F11,
            KC.F4,
            KC.F5,
            KC.F6,
            KC.SLCK,
            XX,
            LSFT,
            LCTL,
            LALT,
            LGUI,
            XX,
            XX,
            KC.F10,
            KC.F1,
            KC.F2,
            KC.F3,
            KC.PAUS,
            XX,
            XX,
            XX,
            XX,
            XX,
            KC.TD(XX, DF(9), **tt),
            KC.TD(XX, DF(6), **tt),
            RALT,
            XX,
            XX,
            XX,
            KC.APP,
            KC.SPC,
            KC.TAB,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
        ],
    ]

    layer_names_list = [
        "Base",
        "Extra",
        "Tap",
        "Button",
        "Nav",
        "Mouse",
        "Media",
        "Num",
        "Sym",
        "Fun",
    ]
    return keyboard, layer_names_list
