version: "3"

tasks:
  setup-docker:
    cmd: |-
      echo "set up the commands below if you haven't, i'll finish the logic later here"
      exit 1
      docker volume create --driver local -o o=bind -o type=none \
        -o device="$PWD" zmk-config
      devcontainer up --workspace-folder "$(pwd)"  \
        --mount type=volume,source=zmk-config,target=/workspaces/zmk_config

  deploy-right:
    cmd: |-
      cp five_six_right.uf2 /media/adam/NICENANO

  deploy-left:
    cmd: |-
      cp five_six_left.uf2 /media/adam/NICENANO

  deploy-left:
    cmd: |-
      cp five_six_left.uf2 /media/adam/NICENANO

  draw-layout:
    cmd: |-
      ./boards/shields/five-six/key_template.py --spacing 1 --comment "//" --width {{.CLI_ARGS}}
  build:
    env:
      CONTAINER_NAME: focused_hopper
    cmd: |-
      for side in left right; do
        docker exec -it $CONTAINER_NAME bash -xec "
          cd /workspaces/zmk/app
          west build -b nice_nano -p -- -DSHIELD=five_six_${side} -DZMK_CONFIG=/workspaces/zmk-config
          cp ./build/zephyr/zmk.uf2 /workspaces/zmk-config/five_six_${side}.uf2
          chown $UID:$UID /workspaces/zmk-config/five_six_${side}.uf2
        "
      done
      