from kmk.keys import KC


def configure(keyboard):

    tt = {"tap_time": 400}
    nph = dict(prefer_hold=False, tap_interrupted=True, **tt)
    ph = dict(prefer_hold=True, tap_interrupted=False, **tt)

    A_ord = ord("A")
    for alpha in range(26):
        globals()[chr(alpha + A_ord)] = getattr(KC, chr(alpha + A_ord))
    for name in {
        "HT",
        "LT",
        "LGUI",
        "LALT",
        "LCTL",
        "LSFT",
        "RALT",
        "RCTL",
        "RSFT",
        "RGUI",
        "SLSH",
        "QUOT",
        "DEL",
        "INS",
        "DF",
        "COMM",
        "ESC",
        "SPC",
        "TAB",
        "ENT",
        "RELOAD",
        "MB_LMB",
        "MB_MMB",
        "MB_RMB",
    }:
        globals()[name] = getattr(KC, name)

    XX = KC.NO

    HT_A_LGUI = KC.HT(A, LGUI, **nph)
    HT_DOT_RALT = KC.HT(KC.DOT, RALT, **nph)
    HT_D_LCTL = KC.HT(D, LCTL, **nph)
    HT_E_LCTL = KC.HT(E, LCTL, **nph)
    HT_F_LSFT = KC.HT(F, LSFT, **nph)
    HT_I_ALT = KC.HT(I, LALT, **nph)
    HT_J_LSFT = KC.HT(J, LSFT, **nph)
    HT_K_LCTL = KC.HT(K, LCTL, **nph)
    HT_L_LALT = KC.HT(L, LALT, **nph)
    HT_N_LSFT = KC.HT(N, LSFT, **nph)
    HT_O_GUI = KC.HT(O, LGUI, **nph)
    HT_QUOT_LGUI = KC.HT(QUOT, LGUI, **nph)
    HT_R_LALT = KC.HT(R, LALT, **nph)
    HT_S_LALT = KC.HT(S, LALT, **nph)
    HT_S_LCTL = KC.HT(S, LCTL, **nph)
    HT_T_LSFT = KC.HT(T, LSFT, **nph)
    HT_X_RALT = KC.HT(X, RALT, **nph)
    LT_3SLSH = LT(3, SLSH, **ph)
    LT_3Z = LT(3, Z, **ph)
    LT_4SPC = LT(4, SPC, **ph)
    LT_5TAB = LT(5, TAB, **ph)
    LT_6ESC = LT(6, ESC, **ph)
    LT_7BSPC = LT(7, KC.BSPC, **ph)
    LT_8ENT = LT(8, ENT, **ph)
    LT_9DEL = LT(9, DEL, **ph)
    TD_CW_CAPS = KC.TD(KC.CW, KC.CAPS, **tt)
    TD_DF0 = KC.TD(XX, DF(0), **tt)
    TD_DF1 = KC.TD(XX, DF(1), **tt)
    TD_DF2 = KC.TD(XX, DF(2), **tt)
    TD_DF4 = KC.TD(XX, DF(4), **tt)
    TD_DF5 = KC.TD(XX, DF(5), **tt)
    TD_DF6 = KC.TD(XX, DF(6), **tt)
    TD_DF7 = KC.TD(XX, DF(7), **tt)
    TD_DF8 = KC.TD(XX, DF(8), **tt)
    TD_DF9 = KC.TD(XX, DF(9), **tt)
    TD_RELOAD = KC.TD(XX, RELOAD, **tt)

    #fmt: off
    keyboard.keymap = [
        [
            Q,
            W,
            F,
            P,
            B,
            J,
            L,
            U,
            Y,
            QUOT,
            HT_A_LGUI,
            HT_R_LALT,
            HT_S_LCTL,
            HT_T_LSFT,
            G,
            M,
            HT_N_LSFT,
            HT_E_LCTL,
            HT_I_ALT,
            HT_O_GUI,
            LT_3Z,
            HT_X_RALT,
            C,
            D,
            V,
            LT_5TAB,
            LT_8ENT,
            K,
            H,
            COMM,
            HT_DOT_RALT,
            LT_3SLSH,
            XX,
            LT_6ESC,
            LT_4SPC,
            LT_5TAB,
            LT_8ENT,
            LT_7BSPC,
            LT_9DEL,
            XX,
        ],
        [
            Q,
            W,
            E,
            R,
            T,
            Y,
            U,
            I,
            O,
            P,
            HT_A_LGUI,
            HT_S_LALT,
            HT_D_LCTL,
            HT_F_LSFT,
            G,
            H,
            HT_J_LSFT,
            HT_K_LCTL,
            HT_L_LALT,
            HT_QUOT_LGUI,
            LT_3Z,
            HT_X_RALT,
            C,
            V,
            B,
            LT_5TAB,
            LT_8ENT,
            N,
            M,
            COMM,
            HT_DOT_RALT,
            LT_3SLSH,
            XX,
            LT_6ESC,
            LT_4SPC,
            LT_5TAB,
            LT_8ENT,
            LT_7BSPC,
            LT_9DEL,
            XX,
        ],
        [
            Q,
            W,
            F,
            P,
            B,
            J,
            L,
            U,
            Y,
            QUOT,
            A,
            R,
            S,
            T,
            G,
            M,
            N,
            E,
            I,
            O,
            Z,
            X,
            C,
            D,
            V,
            LT_5TAB,
            LT_8ENT,
            K,
            H,
            COMM,
            KC.DOT,
            SLSH,
            XX,
            ESC,
            SPC,
            TAB,
            ENT,
            KC.BSPC,
            DEL,
            XX,
        ],
        [
            XX,
            LSFT(DEL),
            LCTL(INS),
            LSFT(INS),
            XX,
            XX,
            LSFT(INS),
            LCTL(INS),
            LSFT(DEL),
            XX,
            LGUI,
            LALT,
            LCTL,
            LSFT,
            XX,
            XX,
            LSFT,
            LCTL,
            LALT,
            LGUI,
            XX,
            LSFT(DEL),
            LCTL(INS),
            LSFT(INS),
            XX,
            XX,
            XX,
            XX,
            LSFT(INS),
            LCTL(INS),
            LSFT(DEL),
            XX,
            XX,
            MB_MMB,
            MB_LMB,
            MB_RMB,
            MB_RMB,
            MB_LMB,
            MB_MMB,
            XX,
        ],
        [
            TD_RELOAD,
            TD_DF2,
            TD_DF1,
            TD_DF0,
            XX,
            XX,
            LSFT(INS),
            LCTL(INS),
            LSFT(DEL),
            XX,
            LGUI,
            LALT,
            LCTL,
            LSFT,
            XX,
            TD_CW_CAPS,
            KC.LEFT,
            KC.DOWN,
            KC.UP,
            KC.RGHT,
            XX,
            RALT,
            TD_DF7,
            TD_DF4,
            XX,
            XX,
            XX,
            INS,
            KC.HOME,
            KC.PGDN,
            KC.PGUP,
            KC.END,
            XX,
            XX,
            XX,
            XX,
            ENT,
            KC.BSPC,
            DEL,
            XX,
        ],
        [
            TD_RELOAD,
            TD_DF2,
            TD_DF1,
            TD_DF0,
            XX,
            XX,
            LSFT(INS),
            LCTL(INS),
            LSFT(DEL),
            XX,
            LGUI,
            LALT,
            LCTL,
            LSFT,
            XX,
            XX,
            KC.MS_LT,
            KC.MS_DN,
            KC.MS_UP,
            KC.MS_RT,
            XX,
            RALT,
            TD_DF8,
            TD_DF5,
            XX,
            XX,
            XX,
            XX,
            XX,
            KC.MW_DN,
            KC.MW_UP,
            XX,
            XX,
            XX,
            XX,
            XX,
            MB_RMB,
            MB_LMB,
            MB_MMB,
            XX,
        ],
        [
            TD_RELOAD,
            TD_DF2,
            TD_DF1,
            TD_DF0,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            LGUI,
            LALT,
            LCTL,
            LSFT,
            XX,
            KC.PS_TOG,
            KC.MPRV,
            KC.VOLD,
            KC.VOLU,
            KC.MNXT,
            XX,
            RALT,
            TD_DF9,
            TD_DF6,
            XX,
            XX,
            XX,
            KC.HID,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            XX,
            KC.MSTP,
            KC.MPLY,
            KC.MUTE,
            XX,
        ],
        [
            KC.LBRC,
            KC.N7,
            KC.N8,
            KC.N9,
            KC.RBRC,
            XX,
            TD_DF0,
            TD_DF1,
            TD_DF2,
            TD_RELOAD,
            KC.SCLN,
            KC.N4,
            KC.N5,
            KC.N6,
            KC.EQL,
            XX,
            LSFT,
            LCTL,
            LALT,
            LGUI,
            KC.GRV,
            KC.N1,
            KC.N2,
            KC.N3,
            KC.BSLS,
            XX,
            XX,
            XX,
            TD_DF7,
            TD_DF4,
            RALT,
            XX,
            XX,
            KC.DOT,
            KC.N0,
            KC.MINS,
            XX,
            XX,
            XX,
            XX,
            XX,
        ],
        [
            KC.LCBR,
            KC.AMPR,
            KC.ASTR,
            KC.LPRN,
            KC.RCBR,
            XX,
            TD_DF0,
            TD_DF1,
            TD_DF2,
            TD_RELOAD,
            KC.COLN,
            KC.DLR,
            KC.PERC,
            KC.CIRC,
            KC.PLUS,
            XX,
            LSFT,
            LCTL,
            LALT,
            LGUI,
            KC.TILD,
            KC.EXLM,
            KC.AT,
            KC.HASH,
            KC.PIPE,
            XX,
            XX,
            XX,
            TD_DF8,
            TD_DF5,
            RALT,
            XX,
            XX,
            KC.LPRN,
            KC.RPRN,
            KC.UNDS,
            XX,
            XX,
            XX,
            XX,
        ],
        [
            KC.F12,
            KC.F7,
            KC.F8,
            KC.F9,
            KC.PSCR,
            XX,
            TD_DF0,
            TD_DF1,
            TD_DF2,
            TD_RELOAD,
            KC.F11,
            KC.F4,
            KC.F5,
            KC.F6,
            KC.SLCK,
            XX,
            LSFT,
            LCTL,
            LALT,
            LGUI,
            KC.F10,
            KC.F1,
            KC.F2,
            KC.F3,
            KC.PAUS,
            XX,
            XX,
            XX,
            TD_DF9,
            TD_DF6,
            RALT,
            XX,
            XX,
            KC.APP,
            SPC,
            TAB,
            XX,
            XX,
            XX,
            XX,
        ],
    ]
    #fmt: on
    layer_names_list = [
        "Base",
        "Extra",
        "Tap",
        "Button",
        "Nav",
        "Mouse",
        "Media",
        "Num",
        "Sym",
        "Fun",
    ]
    return keyboard, layer_names_list
