name: Build ZMK firmware for five-six
on: [workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      config_path: "five-six/config"
      build_matrix_path: "five-six/build.yaml"